/*
 * Copyright (c) 2026 Mark Hunter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.fhirfactory.harmonia.model.ergon;

import org.apache.commons.lang3.StringUtils;
import org.hl7.fhir.r5.model.CodeableConcept;
import org.hl7.fhir.r5.model.CodeableReference;
import org.hl7.fhir.r5.model.Coding;
import org.hl7.fhir.r5.model.Task;

import java.util.Arrays;
import java.util.Optional;

/**
 * Enumeration of standard HIE Task Reason categories and codes.
 * <p>
 * <b>Pragma — Task Instance/State</b>: This particular piece of work as it currently exists - will be used
 * wherever Task (as a synthetic FHIR::Task resource) is used within the codebase.
 * <p>
 * Provides mapping to FHIR R5 {@link CodeableConcept} and {@link CodeableReference} structures.
 */
public enum ErgonReasonEnum {

    HIE_SYNTHETIC_TASK(
            "HIE-Synthetic-Task",
            "HIE-Synthetic-Task",
            "Synthetic task generated by HIE gateway or workflow automation"
    ),
    HIE_ADMINISTRATION_TASK(
            "HIE-Administration-Task",
            "HIE-Administration-Task",
            "Administrative or operational task within the HIE platform"
    ),
    HIE_APPROVAL_TASK(
            "HIE-Approval-Task",
            "HIE-Approval-Task",
            "Task requiring clinical, administrative, or compliance approval"
    ),
    HIE_INFORMATION_REQUEST_TASK(
            "HIE-InformationRequest-Task",
            "HIE-InformationRequest-Task",
            "Task requesting additional patient, encounter, or clinical information"
    );

    public static final String TASK_REASON_SYSTEM = "http://fhirfactory.net/hie/task-reason";

    private final String code;
    private final String display;
    private final String description;

    ErgonReasonEnum(String code, String display, String description) {
        this.code = code;
        this.display = display;
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public String getDisplay() {
        return display;
    }

    public String getDescription() {
        return description;
    }

    public String getSystem() {
        return TASK_REASON_SYSTEM;
    }

    /**
     * Converts this HIE task reason into a FHIR R5 {@link CodeableConcept}.
     *
     * @return populated {@link CodeableConcept} with HIE coding system and text
     */
    public CodeableConcept toCodeableConcept() {
        CodeableConcept concept = new CodeableConcept();
        concept.setText(code);
        Coding coding = concept.addCoding();
        coding.setSystem(TASK_REASON_SYSTEM);
        coding.setCode(code);
        coding.setDisplay(display);
        return concept;
    }

    /**
     * Converts this HIE task reason into a FHIR R5 {@link CodeableReference}.
     *
     * @return populated {@link CodeableReference} containing the concept
     */
    public CodeableReference toCodeableReference() {
        CodeableReference reference = new CodeableReference();
        reference.setConcept(toCodeableConcept());
        return reference;
    }

    /**
     * Applies this reason to the given FHIR R5 {@link Task} resource.
     * Adds the reason entry on the Task if not already present.
     *
     * @param task the FHIR Task resource to update
     * @return the updated Task resource
     */
    public Task applyTo(Task task) {
        if (task != null) {
            boolean alreadyPresent = task.hasReason() && task.getReason().stream().anyMatch(r ->
                    r.hasConcept() && (
                            code.equalsIgnoreCase(r.getConcept().getText()) ||
                            (r.getConcept().hasCoding() && r.getConcept().getCoding().stream().anyMatch(c -> code.equalsIgnoreCase(c.getCode())))
                    )
            );
            if (!alreadyPresent) {
                task.addReason(toCodeableReference());
            }
        }
        return task;
    }

    /**
     * Finds a {@link ErgonReasonEnum} by its string code, display, or enum name.
     *
     * @param code text code, display name, or enum name
     * @return optional containing the matching enum if found
     */
    public static Optional<ErgonReasonEnum> fromCode(String code) {
        if (StringUtils.isBlank(code)) {
            return Optional.empty();
        }
        String clean = code.trim();
        return Arrays.stream(values())
                .filter(r -> r.code.equalsIgnoreCase(clean)
                        || r.display.equalsIgnoreCase(clean)
                        || r.name().equalsIgnoreCase(clean)
                        || r.name().replace("_", "-").equalsIgnoreCase(clean))
                .findFirst();
    }

    /**
     * Checks if a FHIR R5 {@link Task} has a reason matching the given code.
     *
     * @param task the Task to check
     * @param reason the HieTaskReason to check for
     * @return true if the Task has the specified reason
     */
    public static boolean hasReason(Task task, ErgonReasonEnum reason) {
        if (task == null || reason == null || !task.hasReason()) {
            return false;
        }
        return task.getReason().stream().anyMatch(r -> {
            if (!r.hasConcept()) {
                return false;
            }
            CodeableConcept concept = r.getConcept();
            if (reason.code.equalsIgnoreCase(concept.getText())) {
                return true;
            }
            if (concept.hasCoding()) {
                return concept.getCoding().stream()
                        .anyMatch(c -> reason.code.equalsIgnoreCase(c.getCode()));
            }
            return false;
        });
    }

    /**
     * Helper to ensure the default HIE synthetic task reason is set on a Task if not already present.
     *
     * @param task the Task resource to check and update
     * @return the updated Task
     */
    public static Task ensureSyntheticTaskReason(Task task) {
        if (task != null) {
            if (!task.hasReason() || task.getReason().isEmpty()) {
                HIE_SYNTHETIC_TASK.applyTo(task);
            }
        }
        return task;
    }

    @Override
    public String toString() {
        return code;
    }
}
