---
apiVersion: v1
kind: Service
metadata:
  name: mllp-gateway
  namespace: harmonia
  labels:
    app.kubernetes.io/name: pylai-mllp-in
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: harmonia-platform
spec:
  ports:
    - port: 2575
      targetPort: 2575
      name: mllp
    - port: 8080
      targetPort: 8080
      name: http
    - port: 9990
      targetPort: 9990
      name: management
  selector:
    app.kubernetes.io/name: pylai-mllp-in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mllp-gateway
  namespace: harmonia
  labels:
    app.kubernetes.io/name: pylai-mllp-in
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: harmonia-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pylai-mllp-in
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pylai-mllp-in
        app.kubernetes.io/component: gateway
        app.kubernetes.io/part-of: harmonia-platform
    spec:
      containers:
        - name: mllp-in
          image: localhost:32000/harmonia/pylai-mllp-in:1.0.0-SNAPSHOT
          env:
            - name: MLLP_HOST
              value: "0.0.0.0"
            - name: MLLP_PORT
              value: "2575"
            - name: INFINISPAN_HOST
              value: "infinispan-1"
            - name: INFINISPAN_PORT
              value: "11222"
            - name: INFINISPAN_USER
              value: "admin"
            - name: INFINISPAN_PASSWORD
              value: "admin"
            - name: PETASOS_BROKER_URL
              value: "tcp://petasos-artemis-discovery:61616"
            - name: PETASOS_BROKER_USER
              value: "admin"
            - name: PETASOS_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harmonia-artemis-secrets
                  key: admin-password
                  optional: true
            - name: TASK_PROCESSOR_URL
              value: "http://task-processor:8080/api/queue/event"
          ports:
            - containerPort: 2575
              name: mllp
            - containerPort: 8080
              name: http
            - containerPort: 9990
              name: management
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
