# ==============================================================================
# Harmonia :: Pylai :: MLLP Gateway Inbound Configuration
# ==============================================================================

mllp.host=0.0.0.0
mllp.port=2575

# Standard Petasos Broker URL
petasos.broker.url=tcp://petasos:61616

# Legacy fallbacks
task.broker.host=petasos
task.broker.port=61616
task.broker.url=tcp://petasos:61616

# Infinispan cache
infinispan.host=infinispan-1
infinispan.port=11222
infinispan.user=admin
infinispan.password=admin
