---
- name: Delete Ingress resources in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete ingress --all --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true

- name: Delete stateless Deployments in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete deployments --all --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true

- name: Delete StatefulSets (Compute only, preserving PVCs) in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete statefulsets --all --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true

- name: Delete Services in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete services --all --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true

- name: Delete ConfigMaps in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete configmaps --all --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true

- name: Delete Secrets in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete secrets harmonia-db-secrets harmonia-artemis-secrets harmonia-infinispan-secrets harmonia-agora-secrets harmonia-synapse-secrets
    --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true

- name: Delete NetworkPolicies in Harmonia namespace
  ansible.builtin.command: >
    microk8s kubectl delete networkpolicies --all --namespace {{ harmonia_namespace }} --ignore-not-found
  become: true
  changed_when: true
