/*
 * Copyright (c) 2026 Mark Hunter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.fhirfactory.harmonia.petasos.api.config;

import java.io.Serializable;
import java.time.Duration;

/**
 * Configuration specific to {@link net.fhirfactory.harmonia.petasos.api.producer.PetasosProducer}.
 */
public final class PetasosProducerConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    private final boolean defaultDurable;
    private final int defaultPriority;
    private final Duration defaultTtl;
    private final boolean syncDurableSend;
    private final boolean autoGenerateDuplicateDetectionId;

    public PetasosProducerConfig(
            boolean defaultDurable,
            int defaultPriority,
            Duration defaultTtl,
            boolean syncDurableSend,
            boolean autoGenerateDuplicateDetectionId) {
        this.defaultDurable = defaultDurable;
        this.defaultPriority = defaultPriority;
        this.defaultTtl = defaultTtl;
        this.syncDurableSend = syncDurableSend;
        this.autoGenerateDuplicateDetectionId = autoGenerateDuplicateDetectionId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static PetasosProducerConfig defaultConfiguration() {
        return builder().build();
    }

    public boolean isDefaultDurable() {
        return defaultDurable;
    }

    public int getDefaultPriority() {
        return defaultPriority;
    }

    public Duration getDefaultTtl() {
        return defaultTtl;
    }

    public boolean isSyncDurableSend() {
        return syncDurableSend;
    }

    public boolean isAutoGenerateDuplicateDetectionId() {
        return autoGenerateDuplicateDetectionId;
    }

    public static final class Builder {
        private boolean defaultDurable = true;
        private int defaultPriority = 4;
        private Duration defaultTtl = null;
        private boolean syncDurableSend = true;
        private boolean autoGenerateDuplicateDetectionId = true;

        public Builder defaultDurable(boolean defaultDurable) {
            this.defaultDurable = defaultDurable;
            return this;
        }

        public Builder defaultPriority(int defaultPriority) {
            this.defaultPriority = defaultPriority;
            return this;
        }

        public Builder defaultTtl(Duration defaultTtl) {
            this.defaultTtl = defaultTtl;
            return this;
        }

        public Builder syncDurableSend(boolean syncDurableSend) {
            this.syncDurableSend = syncDurableSend;
            return this;
        }

        public Builder autoGenerateDuplicateDetectionId(boolean autoGenerateDuplicateDetectionId) {
            this.autoGenerateDuplicateDetectionId = autoGenerateDuplicateDetectionId;
            return this;
        }

        public PetasosProducerConfig build() {
            return new PetasosProducerConfig(
                    defaultDurable,
                    defaultPriority,
                    defaultTtl,
                    syncDurableSend,
                    autoGenerateDuplicateDetectionId
            );
        }
    }
}
