---
apiVersion: v1
kind: Service
metadata:
  name: agora
  namespace: harmonia
  labels:
    app.kubernetes.io/name: agora
    app.kubernetes.io/component: collaboration
    app.kubernetes.io/part-of: harmonia-platform
spec:
  ports:
    - port: 8092
      targetPort: 8092
      name: http-as
    - port: 9992
      targetPort: 9992
      name: management
  selector:
    app.kubernetes.io/name: agora
