---
apiVersion: v1
kind: Secret
metadata:
  name: harmonia-agora-secrets
  namespace: harmonia
  labels:
    app.kubernetes.io/name: agora
    app.kubernetes.io/component: collaboration
    app.kubernetes.io/part-of: harmonia-platform
type: Opaque
stringData:
  hs-token: "agora_hs_token_secure_value_abc123"
  as-token: "agora_as_token_secure_value_def456"
  synapse-admin-token: "synapse_admin_token_secure_value_ghi789"
