---
apiVersion: v1
kind: Secret
metadata:
  name: harmonia-synapse-secrets
  namespace: harmonia
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: collaboration
    app.kubernetes.io/part-of: harmonia-platform
type: Opaque
stringData:
  registration-shared-secret: "synapse_reg_secret_shared_12345"
  macaroon-secret-key: "synapse_macaroon_secret_key_12345"
  form-secret: "synapse_form_secret_12345"
  db-password: "synapse_db_password"
