# ==============================================================================
# Harmonia :: Pylai :: MLLP Gateway Outbound Configuration
# ==============================================================================

mllp.outbound.instance.id=mllp-sender-default
mllp.outbound.queue.prefix=petasos.queue.mllp.outbound
mllp.outbound.port=8087

# Standard Petasos Broker URL
petasos.broker.url=tcp://petasos:61616
petasos.broker.user=admin
petasos.broker.password=admin

# Legacy fallbacks
task.processor.broker.url=tcp://petasos:61616
task.processor.broker.username=admin
task.processor.broker.password=admin

# Infinispan cache
infinispan.host=infinispan-1
infinispan.port=11222
infinispan.user=admin
infinispan.password=admin
